<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-MFMUIIK" name="Tests.TwoThreadsTest" tests="1" failures="1" timestamp="24 אוג 2017 10:46:36 GMT" time="10.070" errors="0">
  <testcase name="test" time="10.070" classname="Tests.TwoThreadsTest">
    <failure type="java.lang.AssertionError" message="Test failed with failures:
The iteration number is less then 5. it&#039;s 5
The iteration number is less then 5. it&#039;s 6
The iteration number is less then 5. it&#039;s 7
The iteration number is less then 5. it&#039;s 8
The iteration number is less then 5. it&#039;s 9
The iteration number is less then 5. it&#039;s 5
The iteration number is less then 5. it&#039;s 6
The iteration number is less then 5. it&#039;s 7
The iteration number is less then 5. it&#039;s 8
The iteration number is less then 5. it&#039;s 9">
      <![CDATA[java.lang.AssertionError: Test failed with failures:
The iteration number is less then 5. it's 5
The iteration number is less then 5. it's 6
The iteration number is less then 5. it's 7
The iteration number is less then 5. it's 8
The iteration number is less then 5. it's 9
The iteration number is less then 5. it's 5
The iteration number is less then 5. it's 6
The iteration number is less then 5. it's 7
The iteration number is less then 5. it's 8
The iteration number is less then 5. it's 9
	at org.testng.Assert.fail(Assert.java:93)
	at Infra.ReporterTest.endTest(ReporterTest.java:94)
	at Tests.TwoThreadsTest.test(TwoThreadsTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Tests.TwoThreadsTest -->
